# Generated by Django 2.2.1 on 2019-07-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('detail', models.CharField(max_length=1200)),
                ('author', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('birth', models.IntegerField(verbose_name='出生年')),
                ('qq', models.BigIntegerField(verbose_name='QQ')),
                ('phone', models.BigIntegerField(verbose_name='手机号')),
                ('self_introduction', models.CharField(max_length=2000, verbose_name='自我介绍')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, '等待面试'), (1, '通过'), (2, '淘汰'), (3, '待定')], default=0)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1200)),
                ('c_time', models.TimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User')),
            ],
        ),
    ]
